### PR TITLE
Ported to Swift 3. Tests have passed 🎉

### PR DESCRIPTION
**Pull request by codeOfRobin**

### CODE REVIEW

**Review by sofbix — APPROVED** [review]
normal, I think It's time to update to Swift 3

**Comment by codeOfRobin** [comment]
@gmertk So, can we merge this PR?

**Comment by chrisballinger** [comment]
I'm not sure if anyone is maintaining this library anymore.

@gmertk Can someone be added as a maintainer?

**Comment by codeOfRobin** [comment]
@chrisballinger I'd be happy to btw, if @gmertk is okay with it. I have a few alternate ideas in mind though (involving using `UITextField`'s `rightView` property), but this is a good starting point as any.

**Comment by gmertk** [comment]
Sure I would be happy to add maintainer(s) since I don't have time lately. I will merge this over the weekend

**Comment by gmertk** [comment]
Hey @codeOfRobin Thank you for this PR. I came here to merge this. However, this is doing much more than porting it to Swift 3. The example looks a lot different. It fails when I write some text, and delete it.
screenshot 2016-11-06 10 53 38

I can add you as a maintainer, but you should keep the library simple, and clear from your company's needs like changing the default domain, color, or adding a method like chalJaBC (not sure why we need this).

**Comment by codeOfRobin** [comment]
Got it. I'll keep a separate fork, and we can try merging some changes from that. 👍

**Pull request closed without merging**
