### PR TITLE
Swift 3 migration 

### PR DESCRIPTION
**Pull request by hamsternik**
For today, apple provides swift 3 as a primary version for developing, so I migrated the codebase. Also, I made some code refactoring.

### CODE REVIEW

**Comment by chrisballinger** [comment]
@hamsternik Thanks! I was about to do this myself. I'm not sure if the maintainer is still active though, considering my Swift 2.3 PR is still open. 

@gmertk Maybe you could add me to help as a maintainer?

**Comment by gmertk** [comment]
Hi @chrisballinger it would be great actually! is it enough to add you as a collaborator?

**Comment by chrisballinger** [comment]
@gmertk That works, thank you!

**Comment by hamsternik** [comment]
OK, thanks @gmertk for your quick response, as I saw, this project is quite popular, looking at the start on the Github page. 
@chrisballinger please, look my PR and, if you will have sufficient policies, please, apply it.

**Comment by chrisballinger** [comment]
@hamsternik Will do, thanks!

**Pull request merged**
